### ISSUE TITLE
Selective noun/verb linkification.

### ISSUE THREAD

**Issue by will-sklenars** [enspiral-cherubi/dREAM-cACHER_interface_1.0#16]
Currently when you read a dream, every noun and verb is linkified. For nouns and verbs that only appear in one dream, it is not useful to have them linkified as there are no other dreams to be rendered on the dreamscape.

The back end should be modified to only render tags that appear in multiple dreams.

**Comment by data-doge** [comment]
Yeahhh nice idea

**Comment by will-sklenars** [comment]
This will be solved with pr https://github.com/enspiral-cherubi/dREAM-cACHER/pull/4 or a later pr.

**Comment by data-doge** [comment]
https://github.com/enspiral-cherubi/dREAM-cACHER/pull/4 merged, closing
