### ISSUE TITLE
A users dream was saved multiple times

### ISSUE THREAD

**Issue by will-sklenars** [enspiral-cherubi/dREAM-cACHER_interface_1.0#17]
For some unknown reason, a users dream was saved 3 or 4 times. Try to figure out why.

**Comment by data-doge** [comment]
I have a feeling that this might be happening when a user clicks the submit button more than once, before the modal has time to close. Might be good to disable the button immediately after click

**Comment by data-doge** [comment]
addressed in https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/34
