### ISSUE TITLE
occasionally, highlighting sphere persists when i click 'my dreams'

### ISSUE THREAD

**Issue by data-doge** [enspiral-cherubi/dREAM-cACHER_interface_1.0#20]

**Comment by data-doge** [comment]
@will-sklenars said that this might have to do with removing dreams from the DOM

**Comment by will-sklenars** [comment]
This will be solved when pr [22](https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/22) or related pr is merged.

**Comment by data-doge** [comment]
#22 merged!
