### ISSUE TITLE
When no user is logged in, dreamscape doesn't render.

### ISSUE THREAD

**Issue by will-sklenars** [enspiral-cherubi/dREAM-cACHER_interface_1.0#25]
With the implementation of `views`, a user not logged in is not able to see the dreamscape. See screenshot of error message. Seems to be that the client is trying to get `views`, but is unauthorised to do so.

![screen shot 2016-02-27 at 7 50 00 pm](https://cloud.githubusercontent.com/assets/11266273/13371466/967bb010-dd8b-11e5-931f-e8604438a198.png)

**Comment by data-doge** [comment]
on it!

**Comment by data-doge** [comment]
fixed in https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/26, closing

**Comment by will-sklenars** [comment]
Nice!
