### ISSUE TITLE
when i cache a dream, its content is stripped, and the 'cache dream' form is not cleared

### ISSUE THREAD

**Issue by data-doge** [enspiral-cherubi/dREAM-cACHER_interface_1.0#4]
[demonstrative gif](http://g.recordit.co/sXjxSmdYlk.gif)

**Comment by will-sklenars** [comment]
Hmmmm interesting. I will take another look at the function which is processing the inputs. Also, It might be a problem with the function that is adding <a> tags to the text before rendering it.  parseDreamString() in the view.js file.

**Comment by will-sklenars** [comment]
I just tested this case you presented, and it seems to be solved now. Nice!
