### ISSUE TITLE
moving mouse around to click on tabs or interact with dialogs, re-orients me when i don't want to be re-oriented

### ISSUE THREAD

**Issue by data-doge** [enspiral-cherubi/dREAM-cACHER_interface_1.0#9]
personally, when i navigate the dreamscape, i like to have a planned direction, so i don't end up clicking on a dream i've just clicked on. so, while navigating, i'd like to be able to click the top tabs without losing my sense of direction. 

i imagine one way to approach this would be to bring up said tabs on doubleclick or keypress. these tabs would appear in the center of the screen. and when they appear, the camera's yaw momentarily stops responding to the mouse's position. when the dialog is closed, the camera would continue responding to yaw. 

i imagine a similar behavior for when the 'new dream', 'show dream', and 'info' dialogs are brought up. where the camera's yaw momentarily stops responding to mouse position until dialog is closed.

my 2c ! feel free to close if this isn't your vibe

**Comment by will-sklenars** [comment]
I agree, the controls working when the user isn't trying to navigate is less than ideal. The controls setup is THREE.FlyControls. Orbit controls have a controls.enabled = true/false setting. But alas flyControls doesn't seem to have a built in way to disable inputs. I haven't had a look under the hood recently though.

Another option could be to disable mouse steering all together, and just use arrow keys for steering. So WASD & arrows controls for nav, mouse just for clicking on things.

What do you think? Would be easy to try out.

**Comment by data-doge** [comment]
ahh damn, mouse steering feels really good for navigation. 

is there a way to destroy flyControls and recreate it on dialog open/close?

**Comment by will-sklenars** [comment]
Mmmmm yeah that could work. Maybe set this.controls = null, and remove
controls.update from the onRenderFunctions array each time a dialog opens.
Then do the opposite when it is closed.

**Comment by data-doge** [comment]
after this commit https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/commit/7b1c818007e9fc6cdfa9187c90f2378dfaa2f90e, when a `read-dream-modal` is opened, `FlyControls` stops flying around. dunno why but hell yeah 

fix will be implemented when https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/18 is merged

**Comment by will-sklenars** [comment]
Woh that is super strange! I wonder why that happened. Do you think this issue can be closed?

**Comment by data-doge** [comment]
it solves a part of this issue (which is a personal issue), but moving my mouse up to the btns that open the dialogs still moves the camera when i don't want it to be moved

if you also think this is an issue, would you be interested in users being able to create new dreams via a menu brought up by double-click  / keypress?

**Comment by data-doge** [comment]
eyyy just linkin to my comment here for ref: https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/issues/19

totally down to explore arrow key navigation instead of mouse navigation

**Comment by data-doge** [comment]
possible soln in https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/27
